### ISSUE TITLE
Error installing pcsaft from PyPi in Python 3.10.2 environment

### ISSUE THREAD

**Issue by chyicap** [zmeri/PC-SAFT#105]
Hello sir,

Thanks for your effort, I am applying this package to polymer solution.
Following prior closed issue, I have used this package under python 3.9 environment.
Recently, I upgraded python version to 3.10 to use other package's latest version (pyqt5, pyinstaller).
It seems that python version interrupt installation via PyPI.
Could you fix this problem? Error message is as below:

----------------

C:\>pip install pcsaft
Collecting pcsaft
  Using cached pcsaft-1.4.1.tar.gz (117 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Channy\AppData\Local\Temp\pip-install-1auyihm9\pcsaft_b2b04194d4a745f3bee5c35f82a0b684\setup.py", line 17, in <module>
          with open("docs/README.rst", "r") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'docs/README.rst'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

-------------------

Very thank you in advance.
Sincerely.

**Comment by zmeri** [comment]
The error occurs because there is no file for Python 3.10 on PyPI. This is
because I had some problem building a wheel for 3.10, so right now there
are only wheels up to Python 3.9. If I remember right, the build tool I use
didn't yet support Python 3.10. At some point support will probably be
added for 3.10, but for now you could either build pcsaft yourself from the
source code using Cython, or you could downgrade to Python 3.9.
