### ISSUE TITLE
Broken pip package?

### ISSUE THREAD

**Issue by vancesteven** [zmeri/PC-SAFT#108]
I'm getting this error when trying to install:

Collecting pcsaft
  Using cached pcsaft-1.4.1.tar.gz (117 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/66/j7knjchx2wsdk6y8df_2vjnw0000gp/T/pip-install-c7e890g1/pcsaft_229a36716bb34eb689e2706ee8d8d9a8/setup.py", line 17, in <module>
          with open("docs/README.rst", "r") as fh:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'docs/README.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by zmeri** [comment]
You didn't say which version of Python you are using, but you seem to be having the same problem as in #105. I think the error occurs because there are only wheels on PyPI up to Python 3.9. My understanding is that when PyPI cannot find a wheel for your system and Python version, then it will try to get the source files and build the wheel. However, since building the wheel for this package requires Cython, the build fails.

The build tool I've used in the past does not seem to support Python 3.10 or higher, which is why I wasn't able to upload wheels for those versions. I don't have time to look into the build issue myself, but if you would like to figure it out and suggest a fix, I could make incorporate the change and rerun the build job. You can always build the package yourself as well. Install the Cython package and run the Cython build command to compile the C++ files and create the wheel. Then you can install the wheel using pip.
